project:
  type: website

website:
  title: "Project Peasants"
  site-url: "https://project-peasants.netlify.app"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
        
author: Arvind V.

format:
  html:
    theme: cosmo
    css: styles.css
    code-block-border-left: "black"
    code-copy: true
    code-links: true
    code-block-bg: "moccasin"
    format-links: true
    highlight-style: espresso
editor: visual

